### ISSUE TITLE
Should be compatible with Snowpack 2.17.0 but isn't (but I can't reproduce)

### ISSUE THREAD

**Issue by pebezo** [svelte-add/postcss#3]
Hi,

I created a brand new folder and ran:
```
npm init svelte@next # No TS, CSS only
npx use-preset babichjacob/svelte-add-postcss --no-ssh  # Update node dependencies = No
npx use-preset babichjacob/svelte-add-tailwindcss --no-ssh # Update node dependencies = No
npm install
npm run dev -- --open
```
I'm getting this:
```
> svelte-test13@0.0.1 dev /c/dev/test/svelte-test13
> svelte-kit dev "--open"

Unexpected option kit.preprocess
Error: Unexpected option kit.preprocess
    at validate (/c/dev/test/svelte-test13/node_modules/@sveltejs/kit/src/api/load_config/index.js:13:10)
    at validate_config (/c/dev/test/svelte-test13/node_modules/@sveltejs/kit/src/api/load_config/index.js:80:20)
    at Object.load_config (/c/dev/test/svelte-test13/node_modules/@sveltejs/kit/src/api/load_config/index.js:63:20)
    at Object.<anonymous> (/c/dev/test/svelte-test13/node_modules/@sveltejs/kit/src/cli.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-test13@0.0.1 dev: `svelte-kit dev "--open"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-test13@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Any ideas what could cause this?

**Comment by pebezo** [comment]
It fixed the issue above, but now I'm seeing this:

```
Error: Failed to load /_app/assets/generated/root.js: NOT_FOUND
    at /c/dev/test/svelte-test14/node_modules/@sveltejs/kit/src/api/dev/loader.js:61:11
    at /c/dev/test/svelte-test14/node_modules/@sveltejs/kit/src/api/dev/index.js:168:14
```
The snowpack version is set to 2.17.0
```
{
	"name": "svelte-test14",
	"version": "0.0.1",
	"scripts": {
		"dev": "svelte-kit dev",
		"build": "svelte-kit build",
		"start": "svelte-kit start"
	},
	"devDependencies": {
		"@sveltejs/adapter-node": "next",
		"@sveltejs/kit": "next",
		"@sveltejs/snowpack-config": "next",
		"svelte": "^3.29.0",
		"@snowpack/plugin-build-script": "^2.0.11",
		"cssnano": "^4.1.10",
		"postcss": "^8.1.6",
		"postcss-load-config": "^3.0.0",
		"postcss-cli": "^8.2.0",
		"snowpack": "2.17.0",
		"svelte-preprocess": "^4.5.2",
		"tailwindcss": "^2.0.1"
	},
	"resolutions": {
		"snowpack": "2.17.0"
	}
}
```

**Comment by babichjacob** [comment]
If you have pnpm can you try `pnpm update && pnpm outdated` and confirm the only thing that's marked as outdated is `snowpack`?

**Comment by pebezo** [comment]
I don't have pnpm, but hopefully npm gives the same output. Here's what I get after running `npm update` and `npm outdated`:
```
Package             Current        Wanted        Latest  Location
@sveltejs/kit  1.0.0-next.8  1.0.0-next.8  1.0.0-next.1  svelte-test14
snowpack             2.17.0        2.17.0        2.18.4  svelte-test14
```

**Comment by babichjacob** [comment]
Oh, I also forgot to say to try running `dev` again

**Comment by pebezo** [comment]
Unfortunately, I get the same thing as before. Here's what the console looks like:
```
snowpack

  http://localhost:3001 • http://172.22.128.1:3001
  Server started in 77ms.

▼ Console

[snowpack] > Listening on http://localhost:3000
```
(no errors in the console)

**Comment by pebezo** [comment]
With `before`, I meant the error in the browser:
```
Error: Failed to load /_app/assets/generated/root.js: NOT_FOUND
    at /c/dev/test/svelte-test14/node_modules/@sveltejs/kit/src/api/dev/loader.js:61:11
    at /c/dev/test/svelte-test14/node_modules/@sveltejs/kit/src/api/dev/index.js:168:14
```
(not the `kit.preprocess` issue, that seems to have been fixed)

**Comment by babichjacob** [comment]
> With `before`, I meant the error in the browser:
> 
> ```
> Error: Failed to load /_app/assets/generated/root.js: NOT_FOUND
>     at /c/dev/test/svelte-test14/node_modules/@sveltejs/kit/src/api/dev/loader.js:61:11
>     at /c/dev/test/svelte-test14/node_modules/@sveltejs/kit/src/api/dev/index.js:168:14
> ```
> 
> (not the `kit.preprocess` issue, that has been fixed)

Understood. I don't know what's going on here.

**Comment by babichjacob** [comment]
This issue is old and I suggest using Snowpack 3, which the latest versions of the preset will install for you (if it wasn't already being used).
